# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbfcb3729e4688ad025786c39c2e19ee091dad52ba19711b5180bee00b7a70f992d907b5bedbf5949fbe5971563d6cb3bb599322687fc7f26d7161dd169d8c24

test:
  secret_key_base: 8926e368f6b79a9f408c9088b1fe59c28c6df105b5246c9492000fa99425f6d14cd99553ec670955a0e510a77ed5260253dc9369d7aad55029d7ad430a44028b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
